### ISSUE TITLE
Repo: take-home-exercise-random-api

### ISSUE THREAD

**Issue by fcalata31** [EarnestResearch/take-home-exercise-random-api#6]
Hello @EarnestResearch/client-platform 👋 . If not, could we archive or delete? Thank you!

**Comment by gydtaai** [comment]
I think it could be useful for future hirings as well. I'd keep it.
@rebeccarich WDYT ?

**Comment by gydtaai** [comment]
actually we could make it private and archive

**Comment by rebeccarich** [comment]
@fcalata31 this is used by both client platform and internal systems for hiring purposes. Let's keep this as is for the moment if that's ok with you?

**Comment by fcalata31** [comment]
Thank you @gydtaai and @rebeccarich for the feedback! We can keep it active and private (if possible pls) given it's actively being used. Although, can we patch the security vulnerabilities on the Security tab? There's a few outstanding ones there. Thank you!

**Comment by rebeccarich** [comment]
@fcalata31 - the fixes have been merged :)

**Comment by fcalata31** [comment]
@rebeccarich thank you! 🙏
